services:
    pgsql:
        container_name: ${COMPOSE_PROJECT_NAME}-pgsql
        build:
            context: pgsql
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
            DB_NAME: ${DB_NAME}
        ports:
            - ${DB_EXPOSED_PORT}:5432
        volumes:
            - ./pgsql/scripts:/docker-entrypoint-initdb.d
    php:
        container_name: ${COMPOSE_PROJECT_NAME}-php
        stdin_open: true
        tty: true
        build:
            context: php
            args:
                PHP_VERSION: ${PHP_VERSION}
                COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
                TIMEZONE: ${TIMEZONE}
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/log
        environment:
            PHP_IDE_CONFIG: serverName=PHPSTORM
    nginx:
        container_name: ${COMPOSE_PROJECT_NAME}-nginx
        build:
            context: nginx
            args:
                PHP_UPSTREAM: ${COMPOSE_PROJECT_NAME}-php
        ports:
            - ${HTTP_EXPOSED_PORT}:80
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/nginx/:/var/log/nginx

